# Generated by Django 6.1.1 on 2026-09-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id_aviso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_aviso', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('autor', models.CharField(max_length=50)),
                ('tipo_destinatario', models.CharField(choices=[('TODOS', 'Todos'), ('ALUNOS', 'Alunos'), ('MOTORISTAS', 'Motoristas')], max_length=10)),
            ],
            options={
                'db_table': 'aviso',
            },
        ),
    ]
